version: '3'

services:
  accounting-system_db:
    container_name: accounting-system_mysql
    image: mysql:5.7
    volumes:
      - accounting-system_data:/var/lib/mysql           # 挂载数据目录
      - ./server/accounting_system.sql:/docker-entrypoint-initdb.d/accounting_system.sql #导入初始数据
      #- ./mysql/config:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: WTv7N6Ei
      MYSQL_DATABASE: accounting_system
      MYSQL_ROOT_PASSWORD: WTv7N6Ei
  accounting-system_phpmyadmin:
    links:
      - accounting-system_db:db
    depends_on:
      - accounting-system_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: WTv7N6Ei
  accounting-system_backend:
    build: ./server/
    container_name: accounting-system_spring-boot
#    volumes:
#      - ./server:/app
    links:
      - accounting-system_db:db
    ports:
      - "8089:8080"
  accounting-system_frontend:
    build: ./client/
    container_name: accounting-system_reactjs
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"

volumes:
  accounting-system_data:
